# useful configuration
VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
NKRO_ENABLE = yes

# LEDs configuration
BACKLIGHT_ENABLE = yes

# QMK options
KEY_OVERRIDE_ENABLE = yes
CAPS_WORD_ENABLE = no
MOUSEKEY_ENABLE = no
KEY_LOCK_ENABLE = yes
PROGRAMABLE_BUTTON_ENABLE = yes
