#pragma once

//#define NO_DEBUG
//#define NO_PRINT

#define BOOTMAGIC_LITE_ROW 3
#define BOOTMAGIC_LITE_COLUMN 7

#define HOLD_ON_OTHER_KEY_PRESS

#define ONESHOT_TAP_TOGGLE 10
#define ONESHOT_TIMEOUT 5000

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 1000
